#!/bin/bash
# (c) J~Net 2021
#
#
# ./add_missing.sh ufw-framework
#
#
path="records/"
input=$1
defaultinput=""
echo "Welcome To Record Creator By (c)J~Net 2021"
if [ "$#" -eq  "0" ]
  then
    read -p "Enter Command To Create A Record For [$defaultinput]: " input
else
    input=$1
fi
#
file="$path/$input.txt"
if [[ -f $file ]]
then
    echo ""
    echo "Record Already Exists @ records/$input.txt"
else
    echo "Creating Record, Please Wait..."
    man $input > $path/$input.txt
    echo "Add Complete!"
    echo ""
    cat $path/$input.txt
read Y

fi
bash menu
