#!/bin/bash
#
#
#
folder="records"
program="7za"
#
echo "Do You Wish To Decompress (1) Or Compress (2) The Records?"
read intent

if [ $intent -eq 1 ]
then
  
    echo "You Selected Decompress"

if [[ -d $folder ]]
then
    echo "$folder Already Exists!"
else
    mkdir $folder
fi

    $program e records.zip -o$folder/ -aoa && rm records.zip
   
else
    echo "You Selected Compress"
    $program a records.zip $folder/*txt
    echo "Attempting To Set Permissions For New file To You $USER"
    sudo chown $USER *.zip
fi
echo "Type q To Quit"
bash menu
