#!/bin/bash
# (c) J~Net 2022
#
# ./menu
#
#
#
echo -e "\e[93mJ~Net PHP Database Menu (c)J~Net 2022"
echo ""
path="." # .
select fname in $path/*; #
do
    echo you picked $fname \($REPLY\)
    ./$fname
    bash menu
    break;
done
bash menu
