#!/bin/bash
#
NOW=`date '+%F_%H:%M:%S'`;
echo "This Will Setup J~Net PHP Database 2021 The Time & Date Is $NOW"
sudo chmod +x menu
sudo chmod +x add_record
sudo chmod +x search_records
sudo chmod +x menu
sudo chmod +x more_info
sudo chmod +x update_record
sudo chmod +x open_record
sudo chmod +x show_records
sudo chmod +x add_missing
sudo chmod +x compression
# Make folkders if required!
#[ ! -d "records" ] && sudo mkdir records
# Check if count file exists!
#[ ! -f "records/count.txt" ] && echo "0" > records/count.txt
# Goto Menu!
bash compression 1
bash menu
